# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-16 18:30
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0007_alter_validators_add_error_messages'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attribue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=250)),
                ('email', models.CharField(default='Email', max_length=250)),
                ('payee', models.BooleanField(default=False)),
                ('etat', models.CharField(max_length=250)),
                ('total', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Total en €')),
                ('remise', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Remise en €')),
                ('voie_livraison', models.CharField(default='Renseignez votre adresse', max_length=250)),
                ('code_postal_livraison', models.CharField(default='Renseignez votre code postal', max_length=250)),
                ('lieu_livraison', models.CharField(default='Renseignez votre ville', max_length=250)),
                ('pays_livraison', models.CharField(default='Renseigner votre pays', max_length=250)),
                ('date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Couleur',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='image')),
            ],
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=60)),
                ('nom', models.CharField(max_length=60)),
                ('prix', models.FloatField(verbose_name='Prix unitaire en € comprenant les frais de livraison')),
                ('description', models.TextField(blank=True, max_length=1000)),
                ('infos', models.CharField(default=' ', max_length=100, verbose_name='Information courte')),
                ('hauteur', models.FloatField(default=0, verbose_name='Hauteur en cm')),
                ('largeur', models.FloatField(default=0, verbose_name='Largeur en cm')),
                ('profondeur', models.FloatField(default=0, verbose_name='Profondeur en cm')),
                ('volume', models.FloatField(default=0, verbose_name='Volume en cm3')),
                ('poids', models.FloatField(default=0, verbose_name='Poids en kg')),
                ('photo1', models.ImageField(upload_to='image/produit')),
                ('photo2', models.ImageField(upload_to='image/produit')),
                ('photo3', models.ImageField(upload_to='image/produit')),
                ('stock', models.PositiveIntegerField(default=1, verbose_name='Stock')),
                ('conditionnement', models.TextField(blank=True, max_length=1000)),
                ('attribues', models.ManyToManyField(to='YWM.Attribue')),
                ('categorie', models.ManyToManyField(to='YWM.Categorie')),
                ('couleurs', models.ManyToManyField(to='YWM.Couleur')),
            ],
        ),
        migrations.CreateModel(
            name='Produit_Cmd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.PositiveIntegerField()),
                ('prix', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Total en €')),
                ('sous_total', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Total en €')),
                ('commande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relationcommande', to='YWM.Commande')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='YWM.Produit')),
            ],
        ),
        migrations.CreateModel(
            name='Remise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=60)),
                ('quantite', models.IntegerField(default=0)),
                ('pourcentage', models.IntegerField(default=0)),
                ('valeur', models.IntegerField(default=0)),
                ('pour_tous', models.BooleanField(default=True)),
                ('pour_pro', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('voie_livraison', models.CharField(default='Renseignez votre adresse', max_length=250)),
                ('code_postal_livraison', models.CharField(default='Renseignez votre code postal', max_length=250)),
                ('lieu_livraison', models.CharField(default='Renseignez votre ville', max_length=250)),
                ('pays_livraison', models.CharField(default='Renseigner votre pays', max_length=250)),
                ('voie_facturation', models.CharField(default='Non renseigné', max_length=250)),
                ('code_postal_facturation', models.CharField(default='Non renseigné', max_length=250)),
                ('lieu_facturation', models.CharField(default='Non renseigné', max_length=250)),
                ('pays_facturation', models.CharField(default='Non renseigné', max_length=250)),
                ('professionnel', models.BooleanField(default=False)),
                ('nom_entreprise', models.CharField(max_length=250, null="Nom de l'entreprise")),
                ('numero_siret', models.CharField(max_length=250, null='Numero Siret')),
            ],
            options={
                'verbose_name_plural': 'users',
                'verbose_name': 'user',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='remise',
            name='utilisateurs',
            field=models.ManyToManyField(null=True, to='YWM.Utilisateur'),
        ),
        migrations.AddField(
            model_name='commande',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relationutilisateur', to='YWM.Utilisateur'),
        ),
    ]
