# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-16 19:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('YWM', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='remise',
            name='utilisateurs',
            field=models.ManyToManyField(blank=True, to='YWM.Utilisateur'),
        ),
    ]
