# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-17 20:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('YWM', '0002_auto_20170216_2053'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='cout_achat',
            field=models.FloatField(default=0, verbose_name="Coût d'achat en € pour l'analyse des coûts"),
        ),
        migrations.AddField(
            model_name='produit',
            name='cout_estimation_livraison',
            field=models.FloatField(default=0, verbose_name="Estimation coût de livraison en € pour l'analyse des coûts"),
        ),
    ]
