# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-18 15:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('YWM', '0003_auto_20170217_2140'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit_cmd',
            name='total_estimation_livraison',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Estimation cout livraison en €'),
        ),
        migrations.AddField(
            model_name='produit_cmd',
            name='total_prix_achat',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Total coût achat en €'),
        ),
    ]
