# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-19 18:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('YWM', '0004_auto_20170218_1604'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='produit_favori',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='YWM.Produit'),
            preserve_default=False,
        ),
    ]
