# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-19 19:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('YWM', '0005_utilisateur_produit_favori'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='utilisateur',
            name='produit_favori',
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='produit_favori',
            field=models.ManyToManyField(blank=True, to='YWM.Produit'),
        ),
    ]
